GET http://localhost:8080/api/lessons/

###
GET http://localhost:8080/api/lessons/1

###
GET http://localhost:8080/api/categories/

###
GET http://localhost:8080/api/categories/1


### LANGUAGES ###
GET http://localhost:8080/api/lang/

###
GET http://localhost:8080/api/lang/2