GET http://localhost:8080/api/lessons/

###
GET http://localhost:8080/api/lessons/1

###
DELETE http://localhost:8080/api/lessons/4

###
POST http://localhost:8080/api/lessons/
Content-type: application/json

{ "title": "text", "description": "text", "category_id": 2}

###
GET http://localhost:8080/api/lessons/with-category-name/

###

GET http://localhost:8080/api/lessons/edit/14

###

// does not work WHY THE HELL?! GETS 404
PUT http://localhost:8080/api/lessons/2
Content-type: application/json

{ "id": 2, "title": "kerta4", "description": "tätä on muokattu taas", "category_id": 2}

