
### SWEDISH WORDS ###
GET http://localhost:8080/api/swe

###
GET http://localhost:8080/api/swe/22

###
DELETE http://localhost:8080/api/swe/35

###
POST http://localhost:8080/api/swe/
Content-type: application/json

{ "word": "elva" }

###

### ENGLISH WORDS ###
GET http://localhost:8080/api/eng

###
GET http://localhost:8080/api/eng/5

###
DELETE http://localhost:8080/api/eng/22

###
POST http://localhost:8080/api/eng/
Content-type: application/json

{ "word": "eleven" }

###

GET http://localhost:8080/api/eng/match-by/1