GET http://localhost:8080/api/lessons/

###
GET http://localhost:8080/api/lessons/1

###
DELETE http://localhost:8080/api/lessons/4

###
POST http://localhost:8080/api/lessons/
Content-type: application/json

{ "title": "text", "description": "text", "category_id": 2}

###
GET http://localhost:8080/api/lessons/with-category-name/

###

GET http://localhost:8080/api/lessons/edit/14

###

// this feature is currently not available
# PUT http://localhost:8080/api/lessons/edit/2
# Content-type: application/json

# { "title": "Cardinal numbers from 11 to 20", "description": "Let’s continue from where we left in the first lesson about cardinal numbers. In this lesson we are learning how to count from eleven to twenty.", "category_id": 2}

