GET http://localhost:8080/api/pairs/

###
GET http://localhost:8080/api/pairs/1

###
DELETE http://localhost:8080/api/pairs/12

###
POST http://localhost:8080/api/pairs/
Content-type: application/json

{ "language1_id": 1, "language1_word_id": 12, "language2_id": 2, "language2_word_id": 12, "lesson_id": 1}

###
GET http://localhost:8080/api/pairs/from-lesson/2


